apiVersion: v2
name: mokey
description: FreeIPA self-service account management portal
type: application
home: https://github.com/neverlless/mokey
sources:
  - https://github.com/neverlless/mokey
version: 0.9.1
appVersion: "1.9.1"
