{{- if not .Values.existingConfigSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mokey.fullname" . }}-config
  labels:
    {{- include "mokey.labels" . | nindent 4 }}
stringData:
  mokey.toml: |
    {{- .Values.config | nindent 4 }}
{{- end }}
